// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gsasso/go-api/internal/app/controller"
	"github.com/gsasso/go-api/internal/app/server"
	"github.com/gsasso/go-api/internal/app/service"
)

// Injectors from wire.go:

func Initialize() *server.CustomerIntelligenceServer {
	customerService := service.ProvideCustomerService()
	customerController := controller.ProvideCustomerIntelligenceController(customerService)
	customerIntelligenceServer := server.ProvideGRPCServer(customerController)
	return customerIntelligenceServer
}
